import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

test('knowledge hub exposes project package import as a first-class source', async () => {
  const appSource = await readFile(new URL('../frontend/src/App.vue', import.meta.url), 'utf8')
  const knowledgeHubSource = await readFile(new URL('../frontend/src/pages/knowledge/KnowledgeHubPanel.vue', import.meta.url), 'utf8')
  const apiSource = await readFile(new URL('../frontend/src/services/api.js', import.meta.url), 'utf8')
  const mockApiSource = await readFile(new URL('../backend/server/mock-api.mjs', import.meta.url), 'utf8')
  const styles = await readFile(new URL('../frontend/src/styles.css', import.meta.url), 'utf8')

  assert.match(knowledgeHubSource, /open-material-tool', 'project-package-import'/)
  assert.match(knowledgeHubSource, /项目包导入/)
  assert.match(knowledgeHubSource, /交互蓝图包导入/)
  assert.match(appSource, /'project-package-import': '项目包导入'/)
  assert.match(appSource, /materialToolModalMode === 'project-package-import'/)
  assert.match(appSource, /interaction-blueprint\.json/)
  assert.match(appSource, /project-package-import-panel/)
  assert.match(appSource, /accept="\.zip,\.tar\.gz"/)
  assert.match(appSource, /import JSZip from 'jszip'/)
  assert.match(appSource, /projectPackageImportForm\.files/)
  assert.match(appSource, /await JSZip\.loadAsync/)
  assert.match(appSource, /PROJECT_PACKAGE_IMAGE_FILE_PATTERN/)
  assert.match(appSource, /entry\.async\('uint8array'\)/)
  assert.match(appSource, /projectPackageImageMimeType\(entry\.name,\s*bytes\)/)
  assert.match(appSource, /entry\.async\('base64'\)/)
  assert.match(appSource, /data:\$\{mimeType\};base64,\$\{base64\}/)
  assert.match(appSource, /files:\s*projectPackageImportForm\.files/)
  assert.match(appSource, /data\?\.blueprintAsset/)
  assert.match(appSource, /data\?\.prototypeAsset/)
  assert.match(appSource, /upsertWorkspaceAssetFromImport\(data\.blueprintAsset\)/)
  assert.match(appSource, /upsertWorkspaceAssetFromImport\(data\.prototypeAsset\)/)
  assert.match(appSource, /knowledgeHubSection\.value = data\?\.prototypeAsset \? 'prototype' : data\?\.blueprintAsset \? 'structure' : 'entries'/)
  assert.match(appSource, /workflowKnowledgeContextDocuments\(8,\s*workflowEntrySnapshot\.input/)
  assert.match(appSource, /function rankWorkflowKnowledgeItems\(/)
  assert.match(appSource, /lastKnowledgePrototypeHotspot/)
  assert.match(appSource, /knowledgePrototypeClickPath/)
  assert.match(appSource, /resolvePrototypeHotspotTarget/)
  assert.match(knowledgeHubSource, /selectedKnowledgePrototypeHotspot/)
  assert.match(knowledgeHubSource, /knowledgePrototypeClickPath/)
  assert.match(knowledgeHubSource, /点击链路/)
  assert.match(knowledgeHubSource, /prototype-demo-feedback/)
  assert.match(styles, /\.prototype-click-path/)
  assert.match(appSource, /latestKnowledgeMarkdownMaterial/)
  assert.match(appSource, /category === 'markdown-blueprint'/)
  assert.match(appSource, /currentKnowledgeBlueprint\.value[\s\S]*latestKnowledgeMarkdownMaterial\.value\?\.content/)
  assert.match(appSource, /交互 Demo/)
  assert.match(appSource, /项目包解析中/)
  assert.match(appSource, /写入知识库/)
  assert.match(appSource, /生成 Markdown 蓝图/)
  assert.match(apiSource, /fromProjectPackage\(config,\s*payload/)
  assert.match(apiSource, /\/api\/knowledge\/from-project-package/)
  assert.match(mockApiSource, /'POST \/api\/knowledge\/from-project-package'/)
  assert.match(mockApiSource, /POST \/api\/workspace\/materials\/import-project-package/)
  assert.match(styles, /\.project-package-import-panel/)
  assert.match(styles, /\.project-package-dropzone/)
  assert.match(styles, /\.project-package-step-list/)
})
